# Generated by Django 4.0.4 on 2022-05-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avito', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
