# Generated by Django 4.0.4 on 2022-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avito', '0005_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
