# Generated by Django 4.0.4 on 2022-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avito', '0006_alter_ad_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
