# Generated by Django 4.0.4 on 2022-05-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avito', '0006_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='seller',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
